<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; CHARSET=UTF-8">
  <title>异常构造函数</title>
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-base.css" />
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-medium.css" />

  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link media="all" rel="stylesheet" type="text/css" href="style.css"/>
 </head>
 <body class="docs" class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="class.exception.html">? Exception</a></li>
      <li style="float: right;"><a href="exception.getmessage.html">Exception::getMessage ?</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="class.exception.html">Exception</a></li>
    <li>异常构造函数</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="exception.construct" class="refentry">
 <div class="refnamediv">
  <h1 class="refname">Exception::__construct</h1>
  <p class="verinfo">(PHP 5, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">Exception::__construct</span> &mdash; <span class="dc-title">异常构造函数</span></p>

 </div>
 
 <div class="refsect1 description" id="refsect1-exception.construct-description">
  <h3 class="title">说明</h3>
  <div class="constructorsynopsis dc-description">
   <span class="modifier">public</span> <span class="methodname"><strong>Exception::__construct</strong></span>(<span class="methodparam"><span class="type">string</span> <code class="parameter">$message</code><span class="initializer"> = &quot;&quot;</span></span>, <span class="methodparam"><span class="type">int</span> <code class="parameter">$code</code><span class="initializer"> = 0</span></span>, <span class="methodparam"><span class="type">?</span><span class="type"><span class="type"><a href="class.throwable.html" class="type Throwable">Throwable</a></span><span class="type"></span></span> <code class="parameter">$previous</code><span class="initializer"> = <strong><code>null</code></strong></span></span>)</div>

  <p class="para rdfs-comment">
   异常构造函数。
  </p>
 </div>

 
 <div class="refsect1 parameters" id="refsect1-exception.construct-parameters">
  <h3 class="title">参数</h3>
  <p class="para">
   <dl>
    
     <dt>
<code class="parameter">message</code></dt>

     <dd>

      <p class="para">
       抛出的异常消息内容。
      </p>
     </dd>

    
    
     <dt>
<code class="parameter">code</code></dt>

     <dd>

      <p class="para">
       异常代码。
      </p>
     </dd>

    
    
     <dt>
<code class="parameter">previous</code></dt>

     <dd>

      <p class="para">
       异常链中的前一个异常。
      </p>
     </dd>

    
   </dl>

  </p>
  <blockquote class="note"><p><strong class="note">Note</strong>: 
   <span class="simpara">
    如果子类的 $code 和 $message 属性已设置，在调用 Exception 父类的构造器时可以省略默认参数。
   </span>
  </p></blockquote>
 </div>


 <div class="refsect1 notes" id="refsect1-exception.construct-notes">
  <h3 class="title">注释</h3>
  <blockquote class="note"><p><strong class="note">Note</strong>: 
   <p class="para">
    <code class="parameter">message</code> <em class="emphasis">不</em>是二进制安全的。
   </p>
  </p></blockquote>
 </div>


</div><div id="usernotes">
 <div class="head">
  <h3 class="title">User Contributed Notes</h3>
 </div>
<div id="allnotes">  <a name="120135""></a>
  <div class="note">
   <strong class="user">ryan dot jentzsch at gmail dot com</strong>
   <a href="#120135" class="date">08-Nov-2016 11:45</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Note that the code parameter is not the same as exit($code).<br />
Also, the code argument in PHP 7 (possibly earlier versions) is cast to an int including negative values. The code below is completely valid:<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">try<br />
{<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">\Exception</span><span class="keyword">(</span><span class="string">'Testing'</span><span class="keyword">, -</span><span class="default">12.12</span><span class="keyword">);<br />
}<br />
catch (</span><span class="default">\Exception $exception</span><span class="keyword">)<br />
{<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">$code </span><span class="keyword">= </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getCode</span><span class="keyword">();<br />
&nbsp;&nbsp;&nbsp; if (</span><span class="default">$code </span><span class="keyword">&lt; </span><span class="default">0</span><span class="keyword">)<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; exit(</span><span class="default">abs</span><span class="keyword">(</span><span class="default">$code</span><span class="keyword">));<br />
&nbsp;&nbsp;&nbsp; }<br />
}</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="112607""></a>
  <div class="note">
   <strong class="user">talksonweb at gmail dot com</strong>
   <a href="#112607" class="date">03-Jul-2013 09:43</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
For those that haven't done exception chaining. Here's an example. <br />
<br />
This allows you to add the previous exception to the next one and give yourself detailed information in the end as to what happened. This is useful in larger applications.<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">function </span><span class="default">theDatabaseObj</span><span class="keyword">(){<br />
&nbsp;&nbsp; &nbsp; if( </span><span class="default">database_object </span><span class="keyword">){<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; return </span><span class="default">database_object</span><span class="keyword">; <br />
&nbsp;&nbsp; &nbsp; }<br />
&nbsp;&nbsp; &nbsp; else{<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; throw new </span><span class="default">DatabaseException</span><span class="keyword">(</span><span class="string">"Could not connect to the database"</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; }<br />
}<br />
<br />
function </span><span class="default">updateProfile</span><span class="keyword">( </span><span class="default">$userInfo </span><span class="keyword">){<br />
&nbsp;&nbsp; &nbsp; try{<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$db </span><span class="keyword">= </span><span class="default">theDatabaseObj</span><span class="keyword">();<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$db</span><span class="keyword">-&gt;</span><span class="default">updateProfile</span><span class="keyword">();<br />
&nbsp;&nbsp; &nbsp; }<br />
&nbsp;&nbsp; &nbsp; catch( </span><span class="default">DatabaseException $e </span><span class="keyword">){<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$message </span><span class="keyword">= </span><span class="string">"The user :" </span><span class="keyword">. </span><span class="default">$userInfo</span><span class="keyword">-&gt;</span><span class="default">username </span><span class="keyword">. </span><span class="string">" could not update his profile information"</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="comment">/* notice the '$e'. I'm adding the previous exception&nbsp; to this exception. I can later get a detailed view of <br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; where the problem began. Lastly, the number '12' is&nbsp; an exception code. I can use this for categorizing my <br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; exceptions or don't use it at all. */ <br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="keyword">throw new </span><span class="default">MemberSettingsException</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">,</span><span class="default">12</span><span class="keyword">,</span><span class="default">$e</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; }<br />
}<br />
<br />
try{<br />
&nbsp;&nbsp; &nbsp; </span><span class="default">updateProfile</span><span class="keyword">( </span><span class="default">$userInfo </span><span class="keyword">);<br />
}<br />
catch( </span><span class="default">MemberSettingsException $e </span><span class="keyword">){<br />
&nbsp;&nbsp; &nbsp; </span><span class="comment">// this will give all information we have collected above. <br />
&nbsp;&nbsp; &nbsp; </span><span class="keyword">echo </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getTraceAsString</span><span class="keyword">();<br />
}<br />
</span><span class="default">?&gt;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="110968""></a>
  <div class="note">
   <strong class="user">mattsch at gmail dot com</strong>
   <a href="#110968" class="date">31-Dec-2012 03:08</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Be aware that while $previous is quite useful in providing exception chaining and better traceability, none of the internal php exceptions (e.g. PDOException, ReflectionException, etc) are called internally within php with $previous in mind.&nbsp; <br />
<br />
So if your code throws an exception, recovers from it, then catches one of these internal php exceptions, recovers from it and throws another exception, you will not know the first exception that was thrown when calling getPrevious.<br />
<br />
See: https://bugs.php.net/bug.php?id=63873</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
</div>
</div>
</div></div></body></html>
